name: Build and Release Plugin

on:
  release:
    types: [published]  # Se ejecutar치 cuando se publique una nueva release en GitHub

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza Ubuntu como sistema operativo para el job

    steps:
    # 1. Clonamos el c칩digo del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar la versi칩n de PHP (en caso de que necesites PHP para alguna validaci칩n)
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    # 3. Crear el archivo ZIP con la estructura correcta del plugin
    - name: Create plugin ZIP
      run: |
        rm -rf funcionalidad-tamaulipas
        mkdir funcionalidad-tamaulipas
        shopt -s dotglob
        cp -r !(funcionalidad-tamaulipas) funcionalidad-tamaulipas/
        zip -r funcionalidad-tamaulipas.zip funcionalidad-tamaulipas
        rm -rf funcionalidad-tamaulipas
    

    # 4. Subir el archivo ZIP como un asset a la release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./funcionalidad-tamaulipas.zip
        asset_name: funcionalidad-tamaulipas.zip
        asset_content_type: application/zip
